
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import DefaultLayoutApp from "@/components/layouts/default-layout";
import { CartProvider } from "@/context/cart";
import NextAuthSessionProvider from "@/components/provider/session-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/next-auth/options";
import { ThemeProvider } from "@/components/provider/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "G4F Shopping",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);

  return (
    <NextAuthSessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <CartProvider>
              <DefaultLayoutApp>
                {children}
              </DefaultLayoutApp>
            </CartProvider>
          </ThemeProvider>
        </body>
      </html>
    </NextAuthSessionProvider>
  );
}