export const data = {
    brands: [
        { brand_id: 1,  brand_name: 'Luminous Glow',    description: 'A premium brand known for radiant skincare and luminous beauty.' },
        { brand_id: 2,  brand_name: 'Velvet Touch',     description: 'Luxury cosmetics with a soft, velvety finish.' },
        { brand_id: 3,  brand_name: 'Urban Bloom',      description: 'Modern cosmetics brand for the confident city dweller.' },
        { brand_id: 4,  brand_name: 'Ethereal Beauty',  description: 'Lightweight makeup designed to enhance natural beauty.' },
        { brand_id: 5,  brand_name: 'Radiant Hue',      description: 'Bold colors and high-pigment formulas for makeup lovers.' },
        { brand_id: 6,  brand_name: 'NaturaLux',        description: 'Eco-conscious cosmetics with natural ingredients.' },
        { brand_id: 7,  brand_name: 'Bliss Botanica',   description: 'Botanical-based skincare and makeup for sensitive skin.' },
        { brand_id: 8,  brand_name: 'Saffron Skin',     description: 'Inspired by ancient beauty rituals with saffron extracts.' },
        { brand_id: 9,  brand_name: 'Glow Theory',      description: 'Science-driven beauty for a lasting glow.' },
        { brand_id: 10, brand_name: 'Noir Chic',        description: 'Classic and timeless beauty products with a Parisian touch.' },
        { brand_id: 11, brand_name: 'Crimson Kiss',     description: 'Lip-focused brand with intense shades and rich textures.' },
        { brand_id: 12, brand_name: 'SilkSkin',         description: 'Silky-smooth foundations and hydrating primers.' },
        { brand_id: 13, brand_name: 'Canvas Cosmetics', description: 'High-definition makeup perfect for photo-ready looks.' },
        { brand_id: 14, brand_name: 'Bloom & Bare',     description: 'Minimalist beauty with skin-first formulas.' },
        { brand_id: 15, brand_name: 'Petal Dew',        description: 'Inspired by floral freshness and gentle hydration.' },
        { brand_id: 16, brand_name: 'Mystique Glow',    description: 'Mystical tones and exotic ingredients for statement looks.' },
        { brand_id: 17, brand_name: 'Halo Hue',         description: 'Illuminators and highlighters for radiant finishes.' },
        { brand_id: 18, brand_name: 'Karmic Colors',    description: 'Ayurvedic-inspired hues with plant-based pigments.' },
        { brand_id: 19, brand_name: 'Verve Vibe',       description: 'Youthful, energetic brand with bold styling.' },
        { brand_id: 20, brand_name: 'Bare Muse',        description: 'Nude-toned beauty products with a modern twist.' },
        { brand_id: 21, brand_name: 'Orchid Essence',   description: 'Luxury skincare and makeup with orchid extracts.' },
        { brand_id: 22, brand_name: 'SugarDust',        description: 'Playful pastels and shimmering textures for fun-loving beauty.' },
        { brand_id: 23, brand_name: 'Matte Charm',      description: 'Expert in matte finishes for a shine-free look.' },
        { brand_id: 24, brand_name: 'Glowgenix',        description: 'Hybrid skincare and makeup with glowing results.' },
        { brand_id: 25, brand_name: 'LunaBloom',        description: 'Celestial-inspired shades and glow-enhancing products.' },
        { brand_id: 26, brand_name: 'Amber Silk',       description: 'Warm tones and buttery textures for everyday wear.' },
        { brand_id: 27, brand_name: 'Rose Rituals',     description: 'Rose-infused makeup and skincare essentials.' },
        { brand_id: 28, brand_name: 'Foxglove Beauty',  description: 'Fierce, feminine cosmetics with bold branding.' },
        { brand_id: 29, brand_name: 'Glimmer Rush',     description: 'Glitter-heavy cosmetics for party and glam nights.' },
        { brand_id: 30, brand_name: 'Pearl Dust',       description: 'Soft shimmer cosmetics with pearl-based ingredients.' },
    ],
}